### ISSUE TITLE
Work on RTR.ch

### ISSUE THREAD

**Issue by pikooh** [pchr-srf/srf-tools#4]
extension doesn't work on rtr.ch
<img width="734" alt="image" src="https://user-images.githubusercontent.com/1488366/146087721-8924711f-0fe8-46a4-8f9e-058f1da3977f.png">

**Comment by pchr-srf** [comment]
momol
![image](https://user-images.githubusercontent.com/21658108/150563326-d6cd1365-c502-4819-8eae-09c8d6900b69.png)
